### ISSUE TITLE
Critical Error in Idempotence Test When Setting Custom Port for Tangd

### ISSUE THREAD

**Issue by shaunjohnso** [linux-system-roles/nbde_server#138]
When configuring a custom port (port 80) for tangd using the playbook at https://github.com/linux-system-roles/nbde_server/blob/main/tasks/tangd-custom-port.yml, a critical error occurs during the idempotence test phase. The error indicates that specific tasks related to managing the tangd custom port and ensuring required services are enabled and at the correct state fail to execute idempotently. This issue was observed during the execution of an Ansible playbook that utilizes the fedora.linux_system_roles.nbde_server and my_tang_wrap roles.

Steps to Reproduce:
Clone the repository containing the nbde_server role.
Configure the playbook to set tangd to listen on port 80.
Create a custom directory /etc/systemd/system/tangd.socket.d.
Inside the /etc/systemd/system/tangd.socket.d directory, create a custom file named maxcon that includes an increase in connections to 1024.
Run the playbook once to apply the configuration.
Run the playbook again to test for idempotence.

Actual Behavior:
The second playbook execution fails the idempotence test with critical errors for the following tasks:

Manage tangd custom port systemd directory (repeatedly listed)
Ensure required services are enabled and at the right state (repeatedly listed)
Create Directory for Telnet Configuration (repeatedly listed)
Configure Maximum Telnet Connections (repeatedly listed)
These errors suggest that the playbook attempts to reapply configurations or settings that should already be in place, indicating a potential issue with how state is checked or managed for these tasks.

Logs:
 CRITICAL Idempotence test failed because of the following tasks:
*  => fedora.linux_system_roles.nbde_server : Manage tangd custom port systemd directory
*  => fedora.linux_system_roles.nbde_server : Manage tangd custom port systemd directory
*  => fedora.linux_system_roles.nbde_server : Ensure required services are enabled and at the right state
*  => fedora.linux_system_roles.nbde_server : Ensure required services are enabled and at the right state
*  => my_tang_wrap: Create Directory for Telnet Configuration
*  => my_tang_wrap : Create Directory for Telnet Configuration
*  => my_tang_wrap : Configure Maximum Telnet Connections
*  => my_tang_wrap : Configure Maximum Telnet Connections

**Comment by richm** [comment]
@shaunjohnso are you able to try out https://github.com/linux-system-roles/nbde_server/pull/139?

**Comment by shaunjohnso** [comment]
@richm tested and passed, confirmed fixed
