### ISSUE TITLE
Warning: Value 512 is outside of the allowed entropy range, adjusting it. 

### ISSUE THREAD

**Issue by lessfoobar** [linux-system-roles/nbde_server#39]
When using the role on new servers (Fedora34, Fedora33, Rhel8 (all minimal installs)) the nbde_server roles produces the following  error:
```
Warning: Value 512 is outside of the allowed entropy range, adjusting it. 
```
then the key is wrong and thus NBDE doesn't work

when creating everything manually it works just fine. I guess there is a problem in the library.

**Comment by richm** [comment]
@sergio-correia any ideas?

**Comment by sergio-correia** [comment]
This is a warning generated by `pwmake` when `clevis` is generating a new passphrase. I will investigate this further, but I believe this issue should be filed under `nbde_client` rather than `nbde_server`.

**Comment by lessfoobar** [comment]
I'm still getting this message, but clevis is working sooo I'll close that also
